#**Este notebook esta dividido en 2 partes: repasaremos conceptos básicos de python y realizaremos un pequeño ejercicio sobre lo viste en la clase de hoy.**

#Parte 1: Conceptos basicos

**Tipos de datos**

In [ ]:
# Enteros: int()
x = 1
y = +135
z = -23

# Reales: float()
x1 = 2.0
y1 = -0.23
z1 = 6.02e23

# Lógicos o booleanos:
x2 = True
y2 = False

# Texto (strings): str()
x3 = "hola"
y3 = 'Ella dijo "Hola"'
z3 = 'Su rut es: 12.345.678-k'

La función print() permite mostrar valores por pantalla. Se puede usar con strings, con variables, números o combinaciones de estas.

**Operaciones matemáticas**

In [ ]:
print('Resultado de suma:', 3+4)
print('Resultado de multiplicación:', 5*2)
print('Resultado de potencia:', 5**2) #potencia
print('Resultado de división:', 12/5) # division
print('Resultado de división entera:', 12//5) # division entera
print('Resultado de modulo:', 7%3) # modulo (resto de la division entera)


Resultado de suma: 7
Resultado de multiplicación: 10
Resultado de potencia: 25
Resultado de división: 2.4
Resultado de división entera: 2
Resultado de modulo: 1


Se pueden usar funciones precargadas

In [ ]:
print(round(3.1415))
print(abs(-33))

3
33


Se pueden importar funciones de otras librerias

In [ ]:
# forma 1:
from math import sqrt

print('Forma 1:',sqrt(4))

# forma 2:
import math
print('Forma 2:',math.sqrt(4))

Forma 1: 2.0
Forma 2: 2.0


**Condicionales**

La sintaxis del condicional es:

```
if condicion:
  expresiones
```

Es obligatorio indentar y usar el ":" al final del if.



In [ ]:
# Ejemplo 1:
nota = int(input("Ingrese su nota: ")) # La función "input" permite ingresar datos por teclado. POr defecto, todo lo ingresado es tipo string.
if nota >= 4.0:
    print("Felicitaciones!!!")

In [ ]:
# Ejemplo 2:
edad = int(input("Cual es su edad? "))
if edad < 18:
    print("Usted es menor de edad")
else:
    print("Usted es adulto")

In [ ]:
# Ejemplo 3
nota = int(input("Ingrese su nota: "))
if nota >= 6.0:
    print("Usted es un alumno destacado.")
elif nota >= 5.0
    print("Usted ha aprobado con algunas dificultades.")
elif nota >= 4.0:
    print("Usted aprobó.")
else:
    print("Nos vemos el próximo semestre.")

**Ciclos**

Existen 2 formas de hacer ciclos: while y for.

Sintaxis del while:



```
while condición:
    instrucciones mientras la condición sea verdadera
```

Sintaxis del for:

```
for variable in secuencia:
    instrucciones
```

el "for" itera sobre la variable "secuencia". Esta variable puede ser un string, alguna estructura de datos (listas, diccionarios, arreglos, etc) o algun archivo.

In [ ]:
# Ejemplo de while
cant = int(input("Ingrese la cantidad de alumnos: "))

cont = 0 #contador de alumnos/notas ingresadas
suma = 0 #notas acumuladas

while cont < cant:
    nota = int(input("Ingrese nota: "))
    suma = suma + nota
    cont = cont + 1

print("El promedio es:", int(round(suma/cont)))

In [ ]:
# Ejemplo de for
s = "hola mundo!"
for caracter in s:
    print("caracter = " + caracter) # podria ser tambien: print('caracter =', caracter)

caracter = h
caracter = o
caracter = l
caracter = a
caracter =  
caracter = m
caracter = u
caracter = n
caracter = d
caracter = o
caracter = !


**Funciones**

Se debe usar la palabra reservada "def" para crear la funcion y "return" para retornar el valor. 

Luego de creada la función, puede ser llamada de un código principal o main.

In [ ]:
#Ejemplo de creación y uso de una función.
def promedio(p1, p2, p3):
    suma = p1 + p2 + p3
    prom = suma / 3
    return prom

n1 = float(input('Ingrese la primera nota: '))
n2 = float(input('Ingrese la segunda nota: '))
n3 = float(input('Ingrese la tercera nota: '))

prom = promedio(n1, n2, n3) # llamado de la función
print('El promedio es:', prom)


Ingrese la primera nota: 3.5
Ingrese la segunda nota: 4
Ingrese la tercera nota: 4.5
El promedio es: 4.0


**Estructuras de datos**

***Listas***

Una lista es una colección ordenada de elementos de cualquier tipo, incluso otras listas.

Sus elementos individuales pueden accederse a través de índices, como con los caracteres de un string.





In [ ]:
# Lista vacía
a = []
b = list()
print(a)
print(b)

# Lista con elementos
a = [1,2,3,4]
palabra = "hola"
b = list([palabra,2,[1,2],'3'])
print(a)
print(b)

# función range()
a = list(range(4,10))
b = list(range(5))
print(a)
print(b)

[]
[]
[1, 2, 3, 4]
['hola', 2, [1, 2], '3']
[4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4]


In [ ]:
# Puede acceder a datos guardados en listas de la siguiente manera:

L = [1,2,3,4,5,6]

print(L[0])
print(L[2])

print(L[1:4])
print(L[-1])

# Se usan los indices (núúmeros enteros) para acceder a los elementos. Se usa el operador rebanador (slice en ingles) para esto. Su forma general es: Lista[a:b:c]

1
3
[2, 3, 4]
6



Métodos para listas

*   Agregar un elemento x: l.append(x)
*   Agregar un elemento x en una posición pos: l.insert(pos,x)
*   Contar la cantidad de ocurrencias de un elemento x: l.count(x)
*   Obtener el índice de un elemento x: l.index(x)
*   Eliminar un elemento x: l.remove(x)
*   Invertir una lista: l.reverse()
*   Ordenar una lista: l.sort()

Existen muchas otras más. Puede investigar por su cuenta para saber mucho más de esta estructura de datos tan versatil.
    
    
    



***Diccionarios***


Un diccionario es una colección no ordenada que permite asociar llaves con valores. Utilizando la llave siempre es posible recuperar, de manera eficiente, el valor asociado.


*   El funcionamiento de diccionarios es similar a cuando se recupera un elemento de una lista usando su índice: L[i]
*   En este caso el índice de la lista es una ''llave'' y el elemento recuperado es el ''valor''




    
    



In [ ]:
#diccionario de telefonos
#llaves: nombres de personas (string)
#valores: numeros de telefono asociados a cada nombre (int)
telefonos = {'Jaimito':5551428, 'Yayita': 5550012, 'Pepito':5552437}

#mostrar por pantalla el telefono de Pepito
print(telefonos['Pepito'])

In [ ]:
# Se pueden crear diccionarios vacios
dicc1 = {} 
dicc2 = dict()
print(dicc1)
print(dicc2)

Se puede *agregar/modificar* un elemento de un diccionario:

Se debe hacer una asignación del diccionario con una llave igual a un valor.

*   Si la llave utilizada no existe en el diccionario, se agrega un nuevo elemento.
*   Si la llave utilizada existe en el diccionario, el valor asociado es modificado.
    


In [ ]:
patas = {'humano': 2, 'pulpo': 8, 'perro': 5, 'gato': 4}
print("Diccionario antes de agregar un valor")
print(patas)
patas['cienpies'] = 100
print("Diccionario despues de agregar un valor")
print(patas)

In [ ]:
#los perros en realidad tienen cuatro patas, cambiar valor en el diccionario
patas["perro"] = 4
print("Diccionario despues de cambiar un valor")
print(patas)

*Eliminar un elemento*

Usando la instrucción del se puede eliminar un elemento del diccionario. Se debe indicar la llave del elemento que se quiere eliminar.


In [ ]:
patas =  {'cienpies': 100, 'humano': 2, 'gato': 4, 'pulpo': 8, 'perro': 4}
print("Diccionario antes de eliminar un elemento")
print(patas)
#eliminando el elemento del diccionario
del patas["pulpo"]
print("Diccionario despues de eliminar un elemento")
print(patas)

*Acceder a elementos de un diccionario*

El valor asociado a la llave k del diccionario d se puede obtener como d[k]:

In [ ]:
patas =  {'cienpies': 100, 'humano': 2, 'gato': 4, 'pulpo': 8, 'perro': 4}
#accediendo y mostrando por pantalla la cantidad de patas de un gato
print("El gato tiene",patas['gato'],"patas")

Puede investigar por su cuenta para saber mucho más de esta estructura de datos.

***Arreglos***

El módulo que provee las estructuras de datos y las funciones para trabajar con arreglos se llama NumPy, y no viene incluído con Python, por lo que hay que instalarlo por separado.

Para usar las funciones provistas por NumPy, debemos importarlas:

In [ ]:
# una forma de importar numpy es así:
import numpy as np

# la parte: as np, es darle un nombre mas corto para referirse a numpy.

El tipo de datos de los arreglos se llama array. Para crear un arreglo nuevo, se puede usar la función "array" pasándole como parámetro la lista de valores que deseamos agregar al arreglo:

In [ ]:
a = np.array([6, 1, 3, 9, 8])
a

array([6, 1, 3, 9, 8])

Hay muchas formas de arreglos que aparecen a menudo en la práctica, por lo que existen funciones especiales para crearlos:



*   zeros(n) crea un arreglo de n ceros;
*   ones(n) crea un arreglo de n unos;
*   arange(a, b, c) crea un arreglo de forma similar a la función range, con las diferencias que a, b y c pueden ser reales, y que el resultado es un arreglo y no una lista;
*   linspace(a, b, n) crea un arreglo de n valores equiespaciados entre a y b.


In [ ]:
print(np.zeros(6))
print(np.ones(5))
print(np.arange(3.0, 9.0))
print(np.linspace(1, 2, 5))

[0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[3. 4. 5. 6. 7. 8.]
[1.   1.25 1.5  1.75 2.  ]


Las limitaciones que tienen los arreglos respecto de las listas son compensadas por la cantidad de operaciones convenientes que permiten realizar sobre ellos.

In [ ]:
a = np.array([55, 21, 19, 11,  9])
b = np.array([12, -9,  0, 22, -9])

# sumar los dos arreglos elemento a elemento
print(a + b)

# multiplicar elemento a elemento
print(a * b)

# restar elemento a elemento
print(a - b)

[67 12 19 33  0]
[ 660 -189    0  242  -81]
[ 43  30  19 -11  18]


El módulo NumPy contiene a su vez otros módulos que proveen funcionalidad adicional a los arreglos y funciones básicos.

El módulo numpy.random provee funciones para crear números aleatorios (es decir, generados al azar), de las cuales la más usada es la función random, que entrega un arreglo de números al azar distribuidos uniformemente entre 0 y 1:

In [ ]:
from numpy.random import random

random(3)

array([0.85940671, 0.15561076, 0.63646794])

Los elementos de un arreglo se pueden acceder con el pperador rebanador al igual que con las listas:

In [ ]:
print(a[0])
print(a[1:4])

55
[21 19 11]


Los arreglos proveen algunos métodos útiles que conviene conocer.

In [ ]:
print(a.min())
print(a.max())
print(a.argmin())
print(a.sum())

9
55
4
115


*Arreglos bidimensionales*

Los arreglos bidimensionales son tablas de valores. Cada elemento de un arreglo bidimensional está simultáneamente en una fila y en una columna.

En matemáticas, a los arreglos bidimensionales se les llama matrices, y son muy utilizados en problemas de Ingeniería.

En un arreglo bidimensional, cada elemento tiene una posición que se identifica mediante dos índices: el de su fila y el de su columna.

Al igual que los arreglos de una dimensión, los arreglos bidimensionales también pueden ser creados usando la función array, pero pasando como argumentos una lista con las filas de la matriz:



In [ ]:
a = np.array([[5.1, 7.4, 3.2, 9.9],
           [1.9, 6.8, 4.1, 2.3],
           [2.9, 6.4, 4.3, 1.4]])
a

array([[5.1, 7.4, 3.2, 9.9],
       [1.9, 6.8, 4.1, 2.3],
       [2.9, 6.4, 4.3, 1.4]])

In [ ]:
# algunas funciones utiles:

print(a.shape)
print(len(a))

(3, 4)
3


Para obtener un elemento de un arreglo, debe indicarse los índices de su fila i y su columna j mediante la sintaxis a[i, j]:

In [ ]:
a = np.array([[ 3.21,  5.33,  4.67,  6.41],
               [ 9.54,  0.30,  2.14,  6.57],
               [ 5.62,  0.54,  0.71,  2.56],
               [ 8.19,  2.12,  6.28,  8.76],
               [ 8.72,  1.47,  0.77,  8.78]])
a[1, 2]

2.14

# Parte 2: ejercicio

Vamos a calcular las distintas frecuencias de un conjunto de datos.


In [48]:
# Vamos a importar un modulo de la libreria de numby llamada random.
from numpy import random

# Vamos a crear datos aleatorios, donde usted decidiráá el largo de estos datos
n = int(input('Ingrese la cantidad de datos: '))

arreglo = np.zeros(n) # vamos a crear un arreglo del tamaño pedido.

i = 0 
while i < len(arreglo):
  numero = random.randint(1,10) # un valor entero aleatorio entre 1 y 10
  arreglo[i] = numero # asignamos el valor en la posicióón i-esima del arreglo
  i = i+1

arreglo

Ingrese la cantidad de datos: 20


array([6., 4., 4., 6., 2., 1., 1., 8., 6., 7., 2., 6., 8., 2., 3., 9., 2.,
       8., 6., 9.])

In [49]:
# calcularemos la frecuencia absoluta de cada número 
d_fa = {}  # creamos un diccionario para contar cuantos números hay de cada uno. La llave será el número y el valor será las veces que aparece ese número en el arreglo.
L = []  # creamos una lista que nos servira para mostrar los datos en orden gracias a la funcion .sort()

for numero in arreglo: # recorremos el arreglo
  if numero not in d_fa: # si el número no existe como llave del diccionario
    d_fa[numero] = 0     # creamos la llave correspondiente al número. le damos valor 0
    L.append(numero)  # agregamos el numero a la lista. Aca nunca habrán 2 números repetidos.
  d_fa[numero] = d_fa[numero] + 1 # aumentamos en 1 el contador asociado al valor de la llave

d_fa

{1.0: 2, 2.0: 4, 3.0: 1, 4.0: 2, 6.0: 5, 7.0: 1, 8.0: 3, 9.0: 2}

In [50]:
# calculamos la frecuencia relativa de cada número
d_fr = {}
for num, frecuencia in d_fa.items():
  d_fr[num] = frecuencia/n

d_fr

{1.0: 0.1,
 2.0: 0.2,
 3.0: 0.05,
 4.0: 0.1,
 6.0: 0.25,
 7.0: 0.05,
 8.0: 0.15,
 9.0: 0.1}

In [51]:
# calcularemos las frecuencias acumuladas. Para eso ordenaremos los números de menor a mayor.
L.sort()  # nos aseguramos de tener los números en orden ascendente

d_faa = {}
d_fra = {}

c = 0
for num in L:
  valor = d_fa[num] + c 
  d_faa[num] = valor
  d_fra[num] = valor/n 
  c = valor

print('Diccionario de frecuencias absolutas acumuladas:')
print(d_faa)
print('Diccionario de frecuencias relativas acumuladas:')
print(d_fra)

Diccionario de frecuencias absolutas acumuladas:
{1.0: 2, 2.0: 6, 3.0: 7, 4.0: 9, 6.0: 14, 7.0: 15, 8.0: 18, 9.0: 20}
Diccionario de frecuencias relativas acumuladas:
{1.0: 0.1, 2.0: 0.3, 3.0: 0.35, 4.0: 0.45, 6.0: 0.7, 7.0: 0.75, 8.0: 0.9, 9.0: 1.0}


In [52]:
# mostramos todos los datos

print('Valor \t Frecuencia absoluta \t Frecuencia Relativa \t Frecuencia absoluta acumulada \t Frecuencia relativa acumulada')
for num in L:
  print(num,'\t\t', d_fa[num], '\t\t\t', d_fr[num], '\t\t\t   ', d_faa[num], '\t\t\t\t   ', d_fra[num])

Valor 	 Frecuencia absoluta 	 Frecuencia Relativa 	 Frecuencia absoluta acumulada 	 Frecuencia relativa acumulada
1.0 		 2 			 0.1 			    2 				    0.1
2.0 		 4 			 0.2 			    6 				    0.3
3.0 		 1 			 0.05 			    7 				    0.35
4.0 		 2 			 0.1 			    9 				    0.45
6.0 		 5 			 0.25 			    14 				    0.7
7.0 		 1 			 0.05 			    15 				    0.75
8.0 		 3 			 0.15 			    18 				    0.9
9.0 		 2 			 0.1 			    20 				    1.0
